// Objective-C API for talking to github.com/akhenakh/regionagogo/mobile Go package.
//   gobind -lang=objc -prefix=Go github.com/akhenakh/regionagogo/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __GoMobile_H__
#define __GoMobile_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoMobileFence;
@class GoMobileGeoDB;

@interface GoMobileFence : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)iso;
- (void)setIso:(NSString*)v;
- (NSString*)name;
- (void)setName:(NSString*)v;
- (NSString*)geoJSON;
- (void)setGeoJSON:(NSString*)v;
@end

@interface GoMobileGeoDB : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (BOOL)close:(NSError**)error;
- (GoMobileFence*)fenceByID:(long)id;
- (BOOL)openDB:(NSString*)path error:(NSError**)error;
- (GoMobileFence*)queryHandler:(double)lat lng:(double)lng;
@end

FOUNDATION_EXPORT GoMobileFence* GoMobileNewFence();

FOUNDATION_EXPORT GoMobileGeoDB* GoMobileNewGeoDB();

#endif
