
// Objective-C API for talking to the following Go packages
//
//	github.com/akhenakh/regionagogo/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_H__
#define __Mobile_H__

#include "GoMobile.h"
#include "GoUniverse.h"

#endif
